name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy

      - name: Check code formatting
        run: |
          clang-format --version
          find . -name "*.cpp" -o -name "*.h" -o -name "*.hpp" | \
          xargs clang-format --dry-run --Werror
